### ISSUE TITLE
[v5.5.0-3293] Could not initialize class com.sun.webkit.WebPage

### ISSUE THREAD

**Issue by serpro69** [mguessan/davmail#101]
Hi,

Getting this error on a fresh system with the latest davmail version.

Runnung on kubuntu 20.04
Installed default dependencies suggested by apt while installing .deb file.

Logs:
```
Date:			Sat Apr 18 17:36:22 CEST 2020 (1587224182656)
Thread:		JavaFX Application Thread
Message #:	17
Level:		ERROR
NDC:			
Category:	davmail.exchange.auth.O365InteractiveAuthenticatorFrame
Message:		java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage Could not initialize class com.sun.webkit.WebPage
Location:	davmail.exchange.auth.O365InteractiveAuthenticatorFrame.handleError(O365InteractiveAuthenticatorFrame.java:309)
Thrown:

Date:			Sat Apr 18 17:36:23 CEST 2020 (1587224183611)
Thread:		ImapConnection-44076
Message #:	18
Level:		ERROR
NDC:			
Category:	davmail.exchange.auth.O365InteractiveAuthenticator
Message:		Authentication failed Could not initialize class com.sun.webkit.WebPage
Location:	davmail.exchange.auth.O365InteractiveAuthenticator.authenticate(O365InteractiveAuthenticator.java:162)
Thrown:

Date:			Sat Apr 18 17:36:23 CEST 2020 (1587224183612)
Thread:		ImapConnection-44076
Message #:	19
Level:		INFO
NDC:			
Category:	davmail.connection
Message:		FAILED - 127.0.0.1:44076 ***@****.**
Location:	davmail.AbstractConnection.logConnection(AbstractConnection.java:156)
Thrown:

Date:			Sat Apr 18 17:36:23 CEST 2020 (1587224183613)
Thread:		ImapConnection-44076
Message #:	20
Level:		ERROR
NDC:			
Category:	davmail
Message:		Authentication failed Could not initialize class com.sun.webkit.WebPage
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
Thrown:
davmail.exception.DavMailException: Authentication failed Could not initialize class com.sun.webkit.WebPage
	at davmail.exchange.auth.O365InteractiveAuthenticator.authenticate(O365InteractiveAuthenticator.java:163)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:183)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:99)
	at davmail.imap.ImapConnection.run(ImapConnection.java:113)
```

**Comment by serpro69** [comment]
Saw an update yesterday - 5.5.1-3299. Tried that - results are the same.

After saw that Ubuntu 20.04 came with pre-installed openjdk-11 (or maybe something else installed that version), removed it from the machine, installed version 8. Not getting an exception anymore, but there's still no pop-up for 2FA of O365.

**Comment by mguessan** [comment]
Looks like /usr/lib/x86_64-linux-gnu/jni/libjfxwebkit.so is missing on Ubuntu 20 with OpenJDK11 + OpenJFX

It's working fine with ZuluFX JRE from https://www.azul.com/downloads/zulu-community/?os=ubuntu&architecture=x86-64-bit&package=jre-fx

so this looks like an Ubuntu packaging issue.

**Comment by serpro69** [comment]
Hi @mguessan , thanks for the response.
As I mentioned I've removed the pre-installed openjdk, and using sdkman for java installations. I've tried several java versions that are available with openjdk. I've also tried manually including the one you've specified and using that. Still not getting an interactive 2FA window.

**Comment by serpro69** [comment]
Found out that alternatives were still pointing to the jre installed with `apt`.
Fixed that and now everything works fine. 

Thanks for pointing me to the fix @mguessan! Cheers.
