### ISSUE TITLE
If davmail can simulate as mobile client like “Windowsmail”

### ISSUE THREAD

**Issue by rickyangtw** [mguessan/davmail#108]
If davmail can simulate as mobile client like “Windowsmail” Or “ios” DeviceType.
Because some exchange server will block mail client in PC so davmail will be block

Please check below link;
https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/manage-devices?view=exchserver-2019

**Comment by aschaap** [comment]
As a last resort, Davmail can pretend to be Outlook via these two settings:

```
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
```
For more information, see https://sourceforge.net/p/davmail/bugs/702/ .

**Comment by mguessan** [comment]
Thanks aschaap, indeed DavMail can impersonate any client application with its clientId.
Sometimes you will also have to adjust user agent.
