### ISSUE TITLE
JavaFX (OpenJFX) is unable to load Microsoft logon form

### ISSUE THREAD

**Issue by mguessan** [mguessan/davmail#12]
O365 interactive logon relies on JavaFX to create a browser window and let user go through authentication steps. However this does not work with all java versions

**Comment by mguessan** [comment]
Versions that fail:
- Oracle JDK jdk1.8.0_172 on windows
- OpenJDK 11 with OpenJFX 11 on debian sid

Versions known to work:
- Oracle JDK 9.0.4, on both windows and linux
- Oracle jdk1.8.0_40 on windows
- OpenJDK8 + OpenJFX 8 on Ubuntu 18

**Comment by mguessan** [comment]
Test class to demonstrate the issue:


`import javafx.application.Application;`
`import javafx.concurrent.Worker;`
`import javafx.scene.Scene;`
`import javafx.scene.control.ProgressBar;`
`import javafx.scene.layout.StackPane;`
`import javafx.scene.web.WebEngine;`
`import javafx.scene.web.WebView;`
`import javafx.stage.Stage;`
`import org.w3c.dom.Document;`

`import javax.xml.transform.OutputKeys;`
`import javax.xml.transform.Transformer;`
`import javax.xml.transform.TransformerFactory;`
`import javax.xml.transform.dom.DOMSource;`
`import javax.xml.transform.stream.StreamResult;`
`import java.io.ByteArrayOutputStream;`
`import java.io.OutputStreamWriter;`

`public class TestO365Scene extends Application {`
`    final static String url = "https://login.microsoftonline.com/common/oauth2/authorize?client_id=00000002-0000-0ff1-ce00-000000000000&redirect_uri=https%3a%2f%2foutlook.office365.com%2fowa%2f";`
`    final static String redirecturi = "https://outlook.office365.com/owa";`

`    String location;`

`    public TestO365Scene() {`
`    }`

    @Override
    public void start(Stage stage) {
        WebView webView = new WebView();
        final WebEngine webViewEngine = webView.getEngine();

        final ProgressBar loadProgress = new ProgressBar();
        loadProgress.progressProperty().bind(webViewEngine.getLoadWorker().progressProperty());

        StackPane hBox = new StackPane();
        hBox.getChildren().setAll(webView, loadProgress);
        Scene scene = new Scene(hBox);
        stage.setScene(scene);

        stage.show();

        webViewEngine.getLoadWorker().stateProperty().addListener((ov, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                System.out.println(webViewEngine.getLocation());
                System.out.println(dumpDocument(webViewEngine.getDocument()));
                loadProgress.setVisible(false);
                location = webViewEngine.getLocation();
                System.out.println("Webview location: " + location);
                // override console.log
                if (location.startsWith(redirecturi)) {
                    System.out.println("Location starts with redirectUri");
                    System.exit(0);
                }
            } else if (newState == Worker.State.FAILED) {
                Throwable e = webViewEngine.getLoadWorker().getException();
                if (e != null) {
                    System.err.println(e + " " + e.getMessage());
                }
            }

        });

        webViewEngine.load(url);
    }

    public String dumpDocument(Document document) {
        String result;
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            Transformer transformer = TransformerFactory.newInstance().newTransformer();
            transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");
            transformer.setOutputProperty(OutputKeys.METHOD, "xml");
            transformer.setOutputProperty(OutputKeys.INDENT, "yes");
            transformer.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
            transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");

            transformer.transform(new DOMSource(document),
                    new StreamResult(new OutputStreamWriter(baos, "UTF-8")));
            result = baos.toString("UTF-8");
        } catch (Exception e) {
            result = e + " " + e.getMessage();
        }
        return result;
    }

    public static void main(String[] argv) {
        try {
            launch(argv);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
`}`

**Comment by mguessan** [comment]
Update: managed to implement a workaround, by overriding form content to disable integrity check:

```java
try {
    URL.setURLStreamHandlerFactory(new URLStreamHandlerFactory() {
        @Override
        public URLStreamHandler createURLStreamHandler(String protocol) {
            if ("https".equals(protocol)) {
                return new sun.net.www.protocol.https.Handler() {
                    @Override
                    protected URLConnection openConnection(URL url, Proxy proxy) throws IOException {
                        System.out.println("openConnection " + url);

                        if (url.toExternalForm().endsWith("/common/handlers/watson")) {
                            System.out.println("Failed: form calls watson");
                        }
                        final HttpsURLConnectionImpl httpsURLConnection = (HttpsURLConnectionImpl) super.openConnection(url, proxy);
                        if ("login.microsoftonline.com".equals(url.getHost())
                                && "/common/oauth2/authorize".equals(url.getPath())) {

                            return new URLConnection(url) {
                                @Override
                                public void connect() throws IOException {
                                    httpsURLConnection.connect();
                                }

                                public InputStream getInputStream() throws IOException {
                                    byte[] content = readFully(httpsURLConnection.getInputStream());
                                    String contentAsString = new String(content, "UTF-8");
                                    System.out.println(contentAsString);
                                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                                    baos.write(contentAsString.replaceAll("integrity", "integrity.disabled").getBytes("UTF-8"));
                                    return new ByteArrayInputStream(baos.toByteArray());
                                }

                                public OutputStream getOutputStream() throws IOException {
                                    return httpsURLConnection.getOutputStream();
                                }

                            };

                        } else {
                            return httpsURLConnection;
                        }
                    }

                };
            }
            return null;
        }
    });
} catch (Throwable t) {
    System.out.println("Unable to register custom protocol handler");
}
`

**Comment by mguessan** [comment]
Update: issue confirmed with OpenJFX team, see:
https://github.com/javafxports/openjdk-jfx/issues/230
and
https://bugs.openjdk.java.net/browse/JDK-8219917

**Comment by TheGloriousDuck** [comment]
I was trying to use your workaround as I am trying to view a Microsoft logon form with JavaFX 8. What is the readFully function?
