### ISSUE TITLE
Remote host terminated the handshake

### ISSUE THREAD

**Issue by hughwilliams94** [mguessan/davmail#127]
When using the latest trunk build of davmail on linux to try to reach my office365 server, I cannot use the email functionality of DavMail. I've tried on Arch Linux and Ubuntu 18.04 with various different jdk versions; all different exchange protocol settings. I can reach the caldav endpoint but exchange always fails with `Remote host terminated the handshake`. How can I further debug?

When trying with the latest trunk on windows, the server can be accessed fine.

**Comment by hughwilliams94** [comment]
Logs: https://gist.github.com/hughwilliams94/a6f0e773cbc05231fa5633d2e674b095

**Comment by mguessan** [comment]
Looks like a misconfiguration on the client side, i.e. beween client and DavMail, not between DavMail and O365.
If your DavMail instance is local you don't need to enable SSL.
