### ISSUE TITLE
logs tree looks weird after clicking "Clear Log Table"

### ISSUE THREAD

**Issue by Ri0n** [mguessan/davmail#14]
![image](https://user-images.githubusercontent.com/52379/49450756-c558ac00-f7ee-11e8-8474-d05f42ff59fb.png)

If I click on any empty icon then I can see some text there.
No all texts disappear. for example "org -> .... -> util" and all the branch of "Categories -> httpclient" has visible names.

**Comment by mguessan** [comment]
Won't fix: this page is based on LogFactor, no longer supported by Log4J team.
I leave it in DavMail as it may help in some cases, but the best way to track davmail log is to open davmail.log directly.
