### ISSUE TITLE
A suitable Version of Java could not be found (Java Version 8 Update 281) 

### ISSUE THREAD

**Issue by Railsimulatornet** [mguessan/davmail#144]
Hello,

Unfortunately, I get the above error message under Windows 2016 x64.

Windows Server 2016 x64 
Java Verion 8 Update 281 (Build 1.8.0_281-b09)
Version Davmail 5.5.1

I can start Davmail.jar manually without any problems. 

Uninstalling and installing Java and Davmail unfortunately does not solve the problem.

**Comment by PObdr** [comment]
I have the same problem. Have you tried running davmail64.exe instad of davmail.exe? That fixed it for me.

**Comment by Railsimulatornet** [comment]
Many Thanks,

with the x64 version it works. :-)

**Comment by PObdr** [comment]
I am happy, it works for you as well. :D
I did all the reinstall tasks (davmail, java, java, java ;) ), tried running the .jar after reading your issue... and then tested out running all the files in the installation folder.

**Comment by mguessan** [comment]
Glad you fixed it yourself, I should probably deprecate 32 bits support now... or at least use 64 bits as default.

Note that we also now have a stand-alone package with embedded JRE.
