### ISSUE TITLE
issue with version 5.0

### ISSUE THREAD

**Issue by LiNk-NY** [mguessan/davmail#15]
Hi Mickaël, @mguessan 

I am having issues with the newest version of `DavMail` version `5.0.0-2801`. 
When I try to authenticate with my usual settings, I get an error message saying
`Login to server localhost with username <domain>\<username> failed.`. 

I reverted to version 4.9.0 and this error goes away and I am able to access my email. 

Thank you for providing this useful software. 

Regards,
Marcel

**Comment by mguessan** [comment]
Probably related to connection mode refactoring, hard to tell without a log file.
=> make sure you set the new davmail.mode setting instead of the old davmail.enableEws
=> check davmail.log for errors

If it still does not work, please send me a WIRE DEBUG log file at mguessan@free.fr

**Comment by LiNk-NY** [comment]
Hi Mickaël, @mguessan 

I deleted the `davmail.enableEws` entry in the `~/.davmail.properties` file but it had not effect.
I was getting the error, "Thunderbird failed to find the settings for your email account".

FWIW, I did notice that the 'colon' is escaped in `davmail.url=https\://domain.company.com/EWS/Exchange.asmx`. 

I'm not sure how to output a WIRE DEBUG log file but I would be happy to send you one
if you can point me to a resource for obtaining the log file. 

Best regards,
Marcel

**Comment by mguessan** [comment]
See http://davmail.sourceforge.net/faq.html, basically just set WIRE logging category to DEBUG

**Comment by LiNk-NY** [comment]
Thanks. I sent it in.

**Comment by LiNk-NY** [comment]
I'm getting bounced emails

**Comment by mguessan** [comment]
Passed through...
I think I got it: 5.0.0 forces direct /EWS/Exchange.asmx when mode is EWS. This is wrong in your case, as main authentication is based on OWA/ADFS
=> should be fixed in trunk, can you please check this ?

**Comment by LiNk-NY** [comment]
I sent an email reply. Thanks
