### ISSUE TITLE
MS deprecation of EWS coming up

### ISSUE THREAD

**Issue by henning-schild** [mguessan/davmail#186]
https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-api-deprecations-in-exchange-web-services-for-exchange/ba-p/2813925

What does that mean for davmail? I guess it will stop working and we will need something based on ms graph?

**Comment by henning-schild** [comment]
Thanks for the answer!

**Comment by Thaodan** [comment]
> Moving to graph API at the moment is not an option: it lacks many of the fundamental APIs needed to retrieve full message content with properties, i.e. the MIME message body required for IMAP implementation.

Would the active sync api that is still active work?
