### ISSUE TITLE
What key is used to encrypt the refresh token?

### ISSUE THREAD

**Issue by DUOLabs333** [mguessan/davmail#218]
I'm trying to use davmail headless. I can get a new refresh token, but davmail needs it encrypted in order to use it. However, in order to do it myself, I need to know how it's encrypted.

**Comment by mguessan** [comment]
DavMail creates an encryption key from client side password, thus it doesn't have any secret stored locally.

You should still be able to use an unencrypted refresh token that will be used as is

**Comment by DUOLabs333** [comment]
So, I can just add the resulting url to `davmail.properties` and it should work as-is?

**Comment by DUOLabs333** [comment]
I tried adding the URL, and then just the code, but none of them worked.

**Comment by DUOLabs333** [comment]
Oh, I figured it out (after reading the source code) --- the main piece of code is this: `requests.post("https://login.microsoftonline.com/common/oauth2/token",
data={"redirect_uri":"https://login.microsoftonline.com/common/oauth2/nativeclient","client_id":"facd6cff-a294-4415-b59f-c5b01937d7bd","grant_type":"authorization_code","code":""},headers={'Content-Type': 'application/x-www-form-urlencoded'})`

**Comment by DUOLabs333** [comment]
Oh, I figure

**Comment by DUOLabs333** [comment]
Oh, I figured it out --- the main piece of code is this: `requests.post("https://login.microsoftonline.com/common/oauth2/token",
data={"redirect_uri":"https://login.microsoftonline.com/common/oauth2/nativeclient","client_id":"", "grant_type":"authorization_code","code":""},headers={'Content-Type': 'application/x-www-form-urlencoded'})`
