### ISSUE TITLE
Disable tray icon flashing

### ISSUE THREAD

**Issue by ErwanLeroux** [mguessan/davmail#24]
Hello,
Is there a way to disable the flashing of the icon in the tray bar ?
I find it very distracting.

I tried the -notray parameter, but i would prefer to keep the icon in the tray, just without flashing.

I am using ubuntu 16.04

**Comment by mguessan** [comment]
Currently the answer is no, there is no way to disable icon switch on activity. A simple workaround would be to replace icons inside davmail.jar.

**Comment by mguessan** [comment]
New setting available in 5.3.0

**Comment by averter** [comment]
I think that this is not working as it should. I've ticked the "Disable tray activity switch" and it didn't stop flashing.
