### ISSUE TITLE
invalid_grant AADSTS9XXXXX: Invalid request. Request is malformed or invalid.

### ISSUE THREAD

**Issue by averter** [mguessan/davmail#248]
I am trying to use office 365 Manual authentication mode, and I am able to login/bypass MFA control, see the white page, but when I paste the url back the window is simply refreshed and there is no login. I am using the following credentials (Outlook)
```
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.oauth.tenantId=
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob

```
and this is the log (some parts obfuscated/changed for obvious reasons)
```
2022-10-27 13:55:00,807 DEBUG [ImapConnection-36106] davmail  - < LOGIN ********
2022-10-27 13:55:17,463 DEBUG [ImapConnection-36106] davmail.http.DavGatewaySSLSocketFactory  - createSocket login.microsoftonline.com 443
2022-10-27 13:55:17,608 DEBUG [ImapConnection-36106] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: fpc][value: Aq6X6xl8l45Bhfjp1AuI4eY][domain: login.microsoftonline.com][path: /][expiry: Sat Nov 26 12:55:17 GMT 2022]
2022-10-27 13:55:17,608 DEBUG [ImapConnection-36106] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: x-ms-gateway-slice][value: estsfd][domain: login.microsoftonline.com][path: /][expiry: null]
2022-10-27 13:55:17,609 DEBUG [ImapConnection-36106] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: stsservicecookie][value: estsfd][domain: login.microsoftonline.com][path: /][expiry: null]
2022-10-27 13:55:17,610 WARN  [ImapConnection-36106] davmail.exchange.ExchangeSession  - All network interfaces down or host unreachable !
2022-10-27 13:55:17,610 DEBUG [ImapConnection-36106] davmail.exchange.ExchangeSession  - java.io.IOException: invalid_grant AADSTS3207413: Invalid request. Request is malformed or invalid.
Trace ID: oif8cd43-4178-4507-fr12-559986da0691
Correlation ID: lk294d96-crfb-45be-91f4-5yu2e44e16c5
Timestamp: 2022-10-27 12:55:17Z
java.io.IOException: invalid_grant AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: blf8cd43-4178-3407-as12-559986daxxxx
Correlation ID: eb294c96-cdfb-45be-91f4-5ba2e44e16c5
Timestamp: 2022-10-27 12:55:17Z
	at davmail.exchange.auth.O365Token.setJsonToken(O365Token.java:83)
	at davmail.exchange.auth.O365Token.executeRequest(O365Token.java:170)
	at davmail.exchange.auth.O365Token.<init>(O365Token.java:72)
	at davmail.exchange.auth.O365Token.build(O365Token.java:175)
	at davmail.exchange.auth.O365ManualAuthenticator.authenticate(O365ManualAuthenticator.java:123)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:182)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
	at davmail.imap.ImapConnection.run(ImapConnection.java:128)
2022-10-27 13:55:17,611 INFO  [ImapConnection-36106] davmail.connection  - FAILED - 127.0.0.1:36106 myusername@myworkplace
2022-10-27 13:55:17,611 ERROR [ImapConnection-36106] davmail  - All network interfaces down or host unreachable !
```
Could it be that the clientID and redirectUri are outdated, hence the invalid request error? Thank you in advance for any help.

**Comment by mguessan** [comment]
clientId and redirectUri look ok, more like code is invalid, however the code is rejected.

Did you try to open normal Outlook desktop ?

**Comment by averter** [comment]
Oh...I am on a linux machine and I have never actually accessed my email account from Outlook desktop (only webmail). Could that be it? I have a windows machine that I have never used but can try to use just for this purpose. Would this "do the trick"? Thanks.

**Comment by averter** [comment]
> clientId and redirectUri look ok, more like code is invalid, however the code is rejected.
> 
> Did you try to open normal Outlook desktop ?

Even after opening Outlook the same error shows up, so that was not probably the issue. Do I need to extract something from Outlook desktop to use in davmail?
Specifically, I went over the MFA steps, seen the white screen webpage and copied and pasted the url in the dialog box. I can send you one of the resulting urls + the corresponding davmail logs if it helps? Thanks.

**Comment by mguessan** [comment]
Sure, do you see a urn: and code= in blank page url ?

**Comment by averter** [comment]
> Sure, do you see a urn: and code= in blank page url ?

I do not...hmmm, only a verify_state and duo_code. Like so
```
https://eu-west.azureauth.duosecurity.com/verify?state=631c48ee519c807fa94b00de7e70cdd7c0b25ea9fa2e0c07a4508792c0bab156&duo_code=HLHb4RoWJDgMjRZzWYEduHUklehbmZsy
```

**Comment by averter** [comment]
@mguessan I noticed that in [sourceforge](https://sourceforge.net/p/davmail/discussion/644057/thread/a7061b73cb/#0e38) you said 

1. "Set clientKeystoreType to MSCAPI to enable access to TPM protected client certificate from Java"
2. this has not been tested in Linux or MacOS

Regarding 1. I don't see a MSCAPI option in davmail, only JKS and PKCS12. I'm not totally sure of what these mean so can't tell if it is normal or not, but just thought it was worth mentioning.

**Comment by averter** [comment]
@mguessan Do you have any thoughts on the above? I am really struggling to handle/track emails without davmail interface... Thank you.

**Comment by mguessan** [comment]
Ok so a bit of context: when device check is enabled on O365 you have to use a device that is "joined" to Azure AD, either a windows device (workplace joined) or a mobile (with enterprise portal).
The device.login.microsoftonline.com endpoint requires a client certificate signed by MS-Organization-Access to validate authentication.

Thus you have to authenticate on a company compliant device to obtain a valid authentication token.

**Comment by averter** [comment]
> Ok so a bit of context: when device check is enabled on O365 you have to use a device that is "joined" to Azure AD, either a windows device (workplace joined) or a mobile (with enterprise portal). The device.login.microsoftonline.com endpoint requires a client certificate signed by MS-Organization-Access to validate authentication.
> 
> Thus you have to authenticate on a company compliant device to obtain a valid authentication token.
> 
> In your case it may be a bit different: we see: https://eu-west.azureauth.duosecurity.com/verify => this looks like a Duo specific check, need to execute this in a context where it succeeds to then get a redirect to O365 and get a Microsoft side token
> 
> Could be a certificate check like device.login on Microsoft side: https://duo.com/docs/trusted-endpoints

Hmm, so essentially you're saying that the check has failed because the laptop from which davmail is being run is not a workplace approved device? I have a windows laptop provided by my workplace, and I was able to send and receive emails from it on outlook. I had to go through a Duo specific check, using a [duo security token](https://www.techstore.uco.edu/duo-security-token.html) (also provided by my workplace), when logging into outlook in the laptop.

Questions:
1- What would I need to do on the windows laptop to obtain the authentication token? Run davmail? Or is it stored somewhere where it can be accessed? 
2- I can do point 1) but will that then allow me to also use davmail on my linux machine? I.e. is the authentication token cross-platform?
3- Also, I've read online and that token would probably expire, in which case I would need to use the windows laptop again?

These security systems are really complex/difficult to work around... :-(

**Comment by averter** [comment]
I've found this post about DUO trusted endpoints on linux https://community.duo.com/t/trusted-endpoint-for-linux/10576
Not good news as far as I can tell...
I'll try to get the authentication code from the windows machine ASAP. If you have any other ideas of things that I can try please let me know.

**Comment by averter** [comment]
@mguessan I've followed these steps in the windows laptop:

1. Opened in a web browser the url with this form: `https://login.microsoftonline.com/common/oauth2/authorize?client_id=d3590ed6-52b3-4102-aeff-aad2292ab01c&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_mode=query&login_hint=myemail%40myworkplace.com&resource=https%3A%2F%2Foutlook.office365.com`
2. I've then copied and pasted the url from the blank webpage in davmail's dialog box on my linux laptop. The url has the following form `https://login.microsoftonline.com/common/federation/OAuth2ClaimsProvider?client-request-id=(a code)&sso_nonce=(another code)&mscrid=(another code)`

Still there is no `urn:` and `code=` in the blank page url. What am I missing here? :-(

**Comment by averter** [comment]
I have managed to solve this by using o365 Interactive. The DUO security system that I had to get through had a bug which prevented davmail's "o365 Interactive" mode to work, but that fortunately has [recently been fixed](https://community.duo.com/t/duo-web-v4-sdk-compatibility-with-javafx-webview/13075/4). Thanks for your help @mguessan
