### ISSUE TITLE
Modern doesn't work

### ISSUE THREAD

**Issue by emptythevoid** [mguessan/davmail#251]
I've tried to use the Modern authentication with Thunderbird on both Ubuntu and Windows 10 to no success. Interactive/Manual work fine, and allow me to use MFA to login.  This is with version 6.0.1.  What can I provide to help troubleshoot this issue?

**Comment by emptythevoid** [comment]
To add to this - on Ubuntu, I tested this with OpenJDK and Oracle JDK 11. On Windows, I just used Oracle Java,

**Comment by mguessan** [comment]
Modern cover less use cases than interactive/manual, as it has to emulate all user interactive authentication flow.
For some simple cases it's possible for others (e.g. Okta or Duo integration) it would be very complex to get right.

**Comment by emptythevoid** [comment]
Understood, thank you.  I wasn't sure if I was doing something wrong or not.  Thank you for Davmail - I really appreciate it.

**Comment by mguessan** [comment]
Thanks for the feedback, will work on improving automated authentication to cover more use cases
