### ISSUE TITLE
Duplicate email in Sent Folder

### ISSUE THREAD

**Issue by floviolleau** [mguessan/davmail#269]
Hi,

Thanks for this great tool and allowing us to connect exchange accounts with Thunderbird on Ubuntu!

I have a small issue, when I send email thru Thunderbird, I have twice the same email in Sent folder.

Is it possible to fix it?
Thanks

**Comment by s-p-turner** [comment]
This isn't a davmail issue. In your Thunderbird "Copies & Folders" mail settings, make sure that the "Place a copy in" checkbox is unchecked. Any sent mail is already automatically placed into the Sent / Sent Items folder on the server. Therefore if you leave this box checked you will end up with two copies of every mail that you send being placed into the folder.

**Comment by floviolleau** [comment]
Thanks
