### ISSUE TITLE
.properties file scambling

### ISSUE THREAD

**Issue by jterrain** [mguessan/davmail#271]
Why does the current version of DavMail, when it runs, take a well-organized .properties file (commented, lines grouped by functionality, etc.)  and (a) strip out all the comments; and (b) reorder the lines into apparently random order?

Is there a way to discontinue this behavior so that the user's preferred .properties file comments/order is retained?

**Comment by mguessan** [comment]
Because initially config file was not designed to be human readable and implementation was based on native java properties file handling.

However I implemented a new logic to load/save config file and keep comments... which is not working.
Need to investigate and fix this, thanks for your feedback

**Comment by atelszewski** [comment]
I support having this improvement as well.
Thank you! :-)

**Comment by atelszewski** [comment]
Worked for me, thanks! :-)
