### ISSUE TITLE
davmail.spec: Please remove CRLF line terminators

### ISSUE THREAD

**Issue by OleHolmNielsen** [mguessan/davmail#278]
I can't build the RPM package owing to CRLF line terminators in the davmail.spec file:

$ file davmail.spec
davmail.spec: lex description, ASCII text, with CRLF line terminators

On a Linux host this is easily fixed:

$ dos2unix davmail.spec

Thanks,
Ole

**Comment by mguessan** [comment]
Right, regression related to a bad copy/paste.

Fixed, thanks for your feedback
