### ISSUE TITLE
ports conflict problem

### ISSUE THREAD

**Issue by dln949** [mguessan/davmail#29]
Running Davmail 5.2.0.2961.1 on Ubuntu 18.04.1, using it with Thunderbird.  

I have successfully used Davmail with Thunderbird on this computer many times.  

Today I tried starting Davmail and got these error messages:  

Unable to bind server socket for SMTP on port 1025: port not allowed or in use by another process
Unable to bind server socket for IMAP on port 1143: port not allowed or in use by another process

When I ran the commands lsof -i :1025 or 1143 in a terminal, I got this output:  

protonmai 19849 user   12u  IPv4  81836      0t0  TCP localhost:1025 (LISTEN)
protonmai 19849 user   13u  IPv4  84061      0t0  TCP localhost:1143 (LISTEN)

So, it appears that both Davmail and Protonmail are trying to use the same ports.  Since Protonmail starts up when the computer boots, it grabbed those ports first.  (Correct?)  

I installed Protonmail not long ago, so I figure that is why I am just now seeing this problem.  

What is the best way for me to fix this?  I wish to continue using Protonmail and having it continually running; but while that is going on I'd like also to be able to use Davmail with Thunderbird.  How do I do that?  I am not sure what to change.  (Will Davmail continue to work fine if I just replace the ports 1025 and 1143 with some randomly available ports in the davmail.properties file?)

**Comment by knixeur** [comment]
Yes, you can safely change Davmail ports and point Thunderbird to the newer ones and it will would work (provided the new ports are not used by another program ;) ).
You can just add 1 to those ports, ie 1026 and 1144 or change the second number, 1125/1243, remember ports limit is 65535.

**Comment by dln949** [comment]
> Yes, you can safely change Davmail ports and point Thunderbird to the newer ones and it will would work (provided the new ports are not used by another program ;) ).
> You can just add 1 to those ports, ie 1026 and 1144 or change the second number, 1125/1243, remember ports limit is 65535.

Thank you very much.  A couple followup questions:  

1)  Will the corporate Microsoft Exchange Server that I am connecting to "care" that I've changed the port numbers in Davmail (and for the email account in Thunderbird)?  

2)  (Perhaps one this merits a different issue on Github????)  I now notice that when I start Davmail, it opens a window (titled, "DavMail Gateway") which I have to leave running minimized like any other application.  It used to create an icon in the notification area, now I no longer see that.  I can't say there is anything wrong with this, it is just a change I don't understand.  Should I be concerned?  Why has this change happened?

**Comment by knixeur** [comment]
1. No, Exchange doesn't even know what you're doing besides connecting to EWS.
2. There are too many possibilities were the tray won't be shown, it depends on your Desktop Environment (or Window Manager with some tray), the libraries you've installed, etc. You'll probably see an error or at least useful information if you change Logging settings to DEBUG. It's not a bug in Davmail as it's been reported to work in Ubuntu 18.04 without problems.

**Comment by dln949** [comment]
>     2. There are too many possibilities were the tray won't be shown, it depends on your Desktop Environment (or Window Manager with some tray), the libraries you've installed, etc. You'll probably see an error or at least useful information if you change Logging settings to DEBUG. It's not a bug in Davmail as it's been reported to work in Ubuntu 18.04 without problems.

I turned on the logging, I found this message from DavMail:  

davmail  - System tray is not supported on Gnome, will switch to frame mode

I guess that answers my question.  (I am running Gnome.)  

Thanks for the guidance.
