### ISSUE TITLE
How to trust self-signed certificate

### ISSUE THREAD

**Issue by sino1641** [mguessan/davmail#293]
Hi mguessan,
Much thanks for the great work of the product. 
My company IT is using a self-signed cert with VPN to let employees access exchange owa outside.
When I tried to set up DavMail in my linux desktop with all default config, there is an error message saying:
```
davmail  - > 421 DavMail configuration exception:
Connect exception: javax.net.ssl.SSLPeerUnverifiedException Certificate for <mail.company.com> 
doesn't match any of the subject alternative names: [vpn.company.com]
```
I wonder if there is some approaches to bypass the cert verification or trust the vpn cert?
Thanks again.

**Comment by esabol** [comment]
I'm not sure about DavMail, but, for other Java applications we, we add our self-signed certificates to `$JAVA_HOME/lib/security/cacerts`. Refer to the following for instructions:

https://stackoverflow.com/questions/11617210/how-to-properly-import-a-selfsigned-certificate-into-java-keystore-that-is-avail

**Comment by sino1641** [comment]
@esabol 
Hi Sabol, much thanks for the hint. 
I already tried using it before but it seems the common trust way cannot solve the error of different `subject alternative names` between domains and cert.

**Comment by sino1641** [comment]
I think my scenario should consider as #300 which needs code changde.
