### ISSUE TITLE
[Website Issue] Thunderbird mail setup documentations are outdated.

### ISSUE THREAD

**Issue by FlawlessCasual17** [mguessan/davmail#294]
When ever I try to follow the settings as exactly in your documentation, I always get this error with Thunderbird:
![(thunderbird)v9j8i2_06-20-2023](https://github.com/mguessan/davmail/assets/101912712/f95aade4-1276-4e72-804e-f615cb9623a0)

Perhaps maybe the documentation is outdated? Or do I have to some advanced configuration to make it work for my needs.

**Comment by Zliced13** [comment]
@mguessan Could you please update the Thunderbird setup documentation?

**Comment by pierre-haessig** [comment]
Dear @FlawlessCasual17, I just noticed that there are five setup pages for Thunderbird. Which ones are outdated? Perhaps the Mail Account Setup screenshots in [POP](https://davmail.sourceforge.net/thunderbirdmailsetup.html) and [IMAP](https://davmail.sourceforge.net/thunderbirdimapmailsetup.html) setup pages?

**Comment by FlawlessCasual17** [comment]
All of them. I'm not joking

**Comment by FlawlessCasual17** [comment]
All of them. I'm not joking

**Comment by mguessan** [comment]
Well that's true, most configuration pages are outdated, here is a quick update before we update the actual documentation:

Launch Thunderbird, enter name, email address and password then choose Configure manually:
![image](https://github.com/mguessan/davmail/assets/26726023/cb31b75e-7a90-4151-952d-d47fd6486b7b)

For IMAP incoming server replace hostname with localhost and port with 1143,
for SMTP outgoing server replace hostname with localhost and port with 1025.
(default values, match your DavMail configuration)
![image](https://github.com/mguessan/davmail/assets/26726023/373df55e-5415-472a-b237-18d996d8a86a)

As we don't encrypt local communication between Thunderbird and DavMail you get the warning popup, select I understand the risks and confirm:
![image](https://github.com/mguessan/davmail/assets/26726023/5e37b557-6f3e-4227-b2a2-ebd4b57938b7)

Proceed with authentication:
![image](https://github.com/mguessan/davmail/assets/26726023/36fb3c6b-469d-49d0-858d-07fae72cfd37)

=> Configuration complete

**Comment by FlawlessCasual17** [comment]
> Well that's true, most configuration pages are outdated, here is a quick update before we update the actual documentation:
...

I'll try to follow your steps here to see if they work for me

**Comment by mguessan** [comment]
Documentation updated, upload in progress.

@FlawlessCasual17 authentication troubleshooting became quite complex with Microsoft O365 changes, my recommendation is to validate authentication is working before trying to setup client.
One simple way is to have DavMail running, then access http://localhost:1080 in your web browser and provide your credentials. With O365Interactive you will get the embedded browser popup, with O365Manual a dialog.

**Comment by FlawlessCasual17** [comment]
Good day, I apologize for the delayed response.

When I attempted to follow your instructions, I received this error.

![(thunderbird)E337Q3_06-04-2024](https://github.com/mguessan/davmail/assets/101912712/1200e41d-7cb2-4eae-b595-68d69206a66f)
