### ISSUE TITLE
Permanent auth failure due to (multi-factor) "refresh token failed"

### ISSUE THREAD

**Issue by tst2005** [mguessan/davmail#301]
OS: `Debian 12.1`
davmail: `6.0.1.3390-7`
davmail: `6.1.0.3423-4`
java: `openjdk-17-jre:amd64 17.0.8+7-1~deb12u1`
thunderbird: `1:102.14.0-1~deb12u1`

My davmail has worked for months/years without particular issue.

On Monday morning, I started with a Microsoft problem described in https://github.com/mguessan/davmail/issues/300
Now the Microsoft minor problem was fixed but this temproary problem made my davmail drop his token/authentication.

My davmail is not working when davmails of my colleagues are working properly.

After 2 days investigation I finaly made the following test...

- I setup my account from scratch in a new Linux (freshly installed)
- It fail like the davmail on my laptop.

- I asked one of my colleagues (who has a properly working davmail) to setup his account from scratch on this new Linux  
- It fail too!

My conclusion,
We are unable to setup any new account.
I think all current working davmails, runs because their multi-factor tokens are still valid.
They will all fail in less than one month when the refresh_token will be required.

With davmail O365Interactive:
- davnail ask my email / password / OTP code
- it fail : raise a `Malformed URL` error.

In debug logfile, I found :
```
 ERROR [ImapConnection-58904] davmail.exchange.auth.O365Token  - refresh token failed javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
```
It seems similar to https://github.com/mguessan/davmail/issues/292 but I have no workaround at all.

Regards,

**Comment by esabol** [comment]
Have you tried O365Manual? Might be worth a try.

You shouldn't have to create a new account to test anything. You can just edit your `~/.davmail.properties` file and delete the refreshToken (or restore it from a backup, I hope).

**Comment by tst2005** [comment]
I already tested with or without the `davmail.oauth.myuser@mydomain.com.refreshToken={AES}...base64-value...`
my backup show me that the value stay the same for 1 week ago when it is running correctly.
Now with or without the refreshTokenvalue, it is not working anymore.

My tries with O365Manual :

1) with `davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob` (the value is used for a while with O365Interactive)
- after sending email/password
- after providing the TOTP code, I click on the button to valide the code
- the button becomes disabled, the web animation for loading/waiting never ends.
- I supposed my browser got a redirect to `urn:ietf:wg:oauth:2.0:oob` instead of a https url and he does not understand what to do with it.

2) with `davmail.oauth.redirectUri=` (empty value, the default value seems to be https://login.microsoftonline.com/common/oauth2/nativeclient)
- after providing the TOTP code I got the error page with the message below :
```
AADSTS50011: The redirect URI 'https://login.microsoftonline.com/common/oauth2/nativeclient' specified in the request does not match the redirect URIs configured for the application 'd359####-####-####-####-########b01'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this. 
```
I don't know which value to use for `davmail.oauth.redirectUrl` to get the proper (blank) page and be able to paste back the authentication code.

**Comment by esabol** [comment]
That error means your `davmail.oauth.clientId` is not allowed or wrong. Try setting it to nothing. DavMail should then use a default value, which hopefully works. However, another workaround is to use Outlook desktop's clientId:
```
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
```
I _think_ you should only use that redirectUri when using that clientId. (I'm inferring from @mguessan's reply [here](https://github.com/mguessan/davmail/issues/285#issuecomment-1575613021).) Otherwise,
```
davmail.oauth.redirectUri=https://login.microsoftonline.com/common/oauth2/nativeclient
```
is correct for most cases. That's what I use.

See also https://davmail.sourceforge.net/faq.html if you haven't already read through that.

Hope this helps!

**Comment by tst2005** [comment]
@esabol @mguessan thanks so much ! I revive !
With config
```
davmail.oauth.clientId=
davmail.oauth.redirectUri=https://login.microsoftonline.com/common/oauth2/nativeclient
```
I got the proper URL to paste back.

**Comment by tst2005** [comment]
Thanks again !
I close the issue.
