### ISSUE TITLE
Unable to create calendar entries in Thunderbird

### ISSUE THREAD

**Issue by toomasaas** [mguessan/davmail#304]
I'm using davmail 6.1.0 with Mozilla Thunderbird to access mailbox and calendar on M365.

Previously I was able to create new calendar entries with Thunderbird, but after upgrading Thunderbird from 102 to 115, this no longer works. Every time I try to create a calendar entry, it fails with exception:

`java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key +020000`

Attached is the content of davmail.log when this happens. I wonder if this is something that could be fixed in Davmail, or is the new version of Thunderbird creating calendar entries that are somehow invalid.

[davmail.log.1.txt](https://github.com/mguessan/davmail/files/12392820/davmail.log.1.txt)

**Comment by mguessan** [comment]
Regression related to latest Thunderbird update, fixed in trunk.
