### ISSUE TITLE
Timezone offset problem with longer offsets

### ISSUE THREAD

**Issue by br0xpl** [mguessan/davmail#309]
Issue occurs with latest thunderbird daily. I don't know actually why but thunderbird sends a VCAL like this:

```
BEGIN:VCALENDAR
...
TZOFFSETTO:+010000
TZOFFSETFROM:+012200
DTSTART:18840101T000000
RDATE:18840101T000000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETTO:+020000
TZOFFSETFROM:+010000

```

According to [RFC](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.14) the last seconds component is optional but can appear. 

When davmail gets such vcal it throws 503 with error in VCalendar.java:396 trying to find the offset in ResourceBundle. 

I have fixed this for me adding to the resourcebundle (tzoffsettimezones.properties) a cloned list with 00 at the end.. 

I will send a PR with this fix.

**Comment by esabol** [comment]
Typo in issue title. Change "logner" to "longer".

**Comment by esabol** [comment]
> Additionally I wonder why in the line:
> `+0630=Myanmar Standard Time `
> There is a space at the end - @mguessan isn't this a bug?

Seems like it to me. Would there be any reason to not delete the space at the end of the line?

**Comment by br0xpl** [comment]
> > Additionally I wonder why in the line:
> > `+0630=Myanmar Standard Time `
> > There is a space at the end - @mguessan isn't this a bug?
> 
> Seems like it to me. Would there be any reason to not delete the space at the end of the line?

hmm maybe Exchange for this timezone requires a space at the end (strange bug?)?? If not I think we could delete the space, but would be good to test this somehow?

**Comment by mguessan** [comment]
I used a different approach: normalize TZOFFSETTO instead of duplicating table.

Can you please confirm ?

**Comment by br0xpl** [comment]
looks good @mguessan , thanks!
