### ISSUE TITLE
feature request: only open one browser window at a time

### ISSUE THREAD

**Issue by floatious** [mguessan/davmail#311]
Hello Mickaël,

Thank you very much for your work on davmail.
I use it daily.

I use davmail with:
davmail.mode=O365Interactive

When I wake up, and the remote connection has timed out
(a new 2FA auth is needed), I am greeted by a lot of paste URL windows:
![davmail](https://github.com/mguessan/davmail/assets/7130723/472216a9-0bf9-4f16-9759-bfd03241d8cc)

It would be nice if davmail wouldn't open a new paste URL window,
if there was already a paste URL window open.

**Comment by mguessan** [comment]
Well the real issue is network down detection: currently it assumes authentication failed when it's only a network issue.
Need to investigate this.

**Comment by floatious** [comment]
You are correct, I do not have JFX installed.

I can confirm that switching to O365Manual explicitly does solve the problem
even without the recent davmail changes in trunk.

**Comment by mguessan** [comment]
Would need more details from the logs, but probably related to some dependency issue (regarding openjdk versions).

Let's close this one as it appears fixed for you.
