### ISSUE TITLE
Davmail can not handle username with back slash 

### ISSUE THREAD

**Issue by xtang2010** [mguessan/davmail#324]
Env:  Windows 11
Davmail: 6.2.0 (I also looked source in 6.2.1, as the relevant part is the same, I suspect same behavior)

My organization changed login username format to "domain\username", this caused a lot of problem lately.

Some clients on mobile phone seems working fine, some seems not, here is the list of phones that I have tried.

- iPhone with original email client seems working fine
- Huawei phone with Huawei email client partially work. It can read email by setting IMAP username as "domain\\username", but this username does not work for SMTP (this email client can set only one username for both IMAP and SMTP)
- Microsoft outlook can only work by set the IMAP username as "donamin\\username" and the SMTP username as "domain\username"

After some debug, it turns out this part of code in parseCredentials() (in java/davmail/imap/ImapConnection.java) cause the problem.

```
        int backslashindex = userName.indexOf('\\');
        if (backslashindex > 0) {
            userName = userName.substring(0, backslashindex) + userName.substring(backslashindex + 1);
        } 
```

iPhone seems automatically sending "domain\\\\username" (even though there is only one backslash in username), while other client sending exactly username.

I am not sure what the protocol says, but after I change the code to something below, it works for all clients (with username set to "domain\client")

```
        if (userName.contains("\\\\")) {
            userName = userName.replaceAll("\\\\", "\\");
        }

```

**Comment by mguessan** [comment]
Well technically DavMail can handle username with a back slash, it just is not aware that iOS randomly decided to escape this backslash ;-)

Anyway I don't see any reason for regression with the proposed patch, will merge it as is

**Comment by esabol** [comment]
@xtang2010: You closed the issue prematurely. There's been no commit yet.
