### ISSUE TITLE
Need to store mutable oath refresh token somewhere other than davmail.properties

### ISSUE THREAD

**Issue by KeithHanlan** [mguessan/davmail#335]
The davmail.properties file is a configuration file that should remain fairly static. I prefer to maintain it under version control so that I can safely make and revert changes. (Yes, I maintain many of my core dot files in a git repo.)

Unfortunately, this same file is used to store the ever-changing `davmail.oauth.keith.hanlan@ericsson.com.refreshToken` value.

That means that the file is constantly showing as "modified" in my repo. This prevents merging other changes. 

Can we please have a configuration setting that lets us define an alternate location for this value?

Thank you,
Keith

**Comment by tmcqueen-materials** [comment]
You can use `davmail.oauth.tokenFilePath` to set a separate file in which to store the often-changing tokens.

**Comment by KeithHanlan** [comment]
Bloody awesome! I looked for something like that but failed to find it. Thank you!
