### ISSUE TITLE
Can't delete a single occurrence of a recurring event

### ISSUE THREAD

**Issue by logological** [mguessan/davmail#337]
I'm using davmail 6.2.1 and Thunderbird 115.7.0 on openSUSE Tumbleweed.  Davmail is connecting to a remote calendar via O365Manual.  Deleting a single occurrence of a recurring event from the calendar seems to have no effect.

Reproducibility: Always

Steps to reproduce:
1. In Thunderbird, create a recurring event on the Davmail calendar.  Verify at https://outlook.office.com/calendar/view/month that this event gets synchronized to the remote server.
2. In Thunderbird, right-click on one instance of the recurring event and select "Delete Event".  
3. In the "Delete Repeating Event" dialog that appears, press the "Delete only this occurrence" button.

Observed behaviour:
1. Nothing seems to happen.  The occurrence remains visible in the calendar, both in Thunderbird and at https://outlook.office.com/calendar/view/month.

Expected behaviour:
1. The single occurrence of the recurring event should be removed from the Davmail calendar, and this removal should be synchronized with the remote calendar.

Thunderbird does not emit any error message when the user tries to delete the event (not even in the error console).  The Davmail log indicates that the event is being deleted but I see no indication of any error condition.  I can provide the log if you can provide advice on how to anonymize it.

The problem is restricted to deleting a single occurrence of a recurring event.  There is no problem when deleting all occurrences of a recurring event.

**Comment by mguessan** [comment]
Issue confirmed, working on a fix, basically the EXDATE value is not properly converted and ignores timezone.
As it was working before I assume dates were previously managed as UTC values by Thundebird
