### ISSUE TITLE
sharing_metadata.xml

### ISSUE THREAD

**Issue by ceesb** [mguessan/davmail#34]
Hi,

my Outlook-using colleagues  found a way to send me "shared calendars" that appear to me in the form of [sharing_metadata.xml](https://willcode4foodblog.wordpress.com/2012/04/13/understanding-sharing-invitation-requests-ews-managed-api-1-2-part-1/) attachments. Can I open these using davmail + Thunderbird + Lightning? If so, how?

I think you're are discussing it on [sourceforge](https://sourceforge.net/p/davmail/discussion/644057/thread/1b679c1c/), and I run into the same problem that http://localhost:1080/users/user@company.com/calendar/SharedCalendarName is not accessible, but neither is http://localhost:1080/users/user@company.com/calendar/. Any ideas why this apparently still works for the Outlook users?

Thanks!
Cees

**Comment by mguessan** [comment]
DavMail won't help on client side invitation handling. However, once you accept (e.g. over OWA) you should have access to the target folder.

For shared calendars non standard and in subfolders, I am considering a new way to access folder by FolderId instead of name.

**Comment by ceesb** [comment]
Yeah I think I'm running into issues that are not related to Davmail. If an Outlook user creates a calendar and shares it with me, I cannot accept it in OWA; it'll return an error that the calendar doesn't exist. If I create a calendar in OWA and share it with the Outlook user, all is well. If you've seen this issue and know a work-around please let me know.
