### ISSUE TITLE
Create davmail user/group per new conventions in RPM 4.19

### ISSUE THREAD

**Issue by logological** [mguessan/davmail#356]
When trying to install the DavMail RPM from the Open Build Service repository on openSUSE, Zypper displays the following error message:

> Problem: 1: nothing provides 'group(davmail)' needed by the to be installed davmail-6.2.2-3.4.noarch
>  Solution 1: do not install davmail-6.2.2-3.4.noarch
>  Solution 2: break davmail-6.2.2-3.4.noarch by ignoring some of its dependencies
> 
> Choose from above solutions by number or cancel [1/2/c/d/?] (c): 

A similar problem probably occurs when trying to install the DavMail packages on any OS that uses RPM >= 4.19, and is due to a change in how that version of RPM handles users and groups.  This issue and the possible workarounds for packagers is discussed in [this openSUSE Factory mailing list post](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/HG2JKUIKDTWQQIQSA43A4VWHX7YKJQT3/).

I will submit a patch shortly via OBS.

**Comment by logological** [comment]
Patch submitted as [Request 1176523](https://build.opensuse.org/request/show/1176523).

**Comment by esabol** [comment]
I think this issue can be closed?

**Comment by logological** [comment]
Yes, looks like the patch I proposed on OBS was applied to the GitHub repository.  It's still not in the official RPM but I suppose @mguessan is going to do that for the next release.
