### ISSUE TITLE
DavMail: iOS and UFT-8 characters = not good friends..?

### ISSUE THREAD

**Issue by Exuskazera** [mguessan/davmail#36]
Hello everyone,

first of all: great work you've done here. Really easy to set up and to use. There's just one thing I have to complain about---
Second: I'm from Germany, we have some special characters like 'ü' or 'ä' and so on. Info will be needed later on.

I have two phones with me, one Android-based and the other one with iOS (work and family). I want to synchronize all my contacts from my Outlook to both iOS and Android using CardDav, which successfully worked out pretty fine. Synchronizing the contact to each phone almost works fine too, but here the problem:
iOS has some difficulties listing contacts that have some UFT-8 symbols in their name or address. Whenever there is someone with such letters in the name, iOS shows it with completely different characters to a point where the name is unreadable.
Also, if you create a new contact, for example, "Müller" it will upload the contact correctly to Outlook! But when it synchronizes the contacts on my phone again, the name looks like 'MÂller". Some minutes later, Outlook shows the contact just as broken as it is on iOS.

Is there a possibility to fix it?

What I've tried was to compare if Android had the same problems, but there weren't any. I also looked into the log for differences. There are some lines that are the same, some that say "UFT-8" or "txt/xml" but many of those don't really help when it comes to the problem. And last I tried to set up my iPad with a different iOS version, but still, no luck. 

I hope you understand my problem. If not, please let me know. I will try to answer as soon as possible.

Thank you for your help in advance!

p.s.: I just remembered, there was a line in the log when I started the DavMail-Client, it said that something wasn't able to load so DavMail had to run in a certain mode in order to work. Does that have something to do with our problem? I'll check that later for the specific line...

**Comment by mguessan** [comment]
Answer to ps: probably an SWT related message, not related to encoding.

I don't really understand how a perfectly working with android/desktop Carddav encoding is broken with iOS, can you please provide additional details/log file content ?

**Comment by Exuskazera** [comment]
Good Morning,

thank you for replying.

I just know the log, which will be generated by DavMail itself and the debug-file by Android.
(Files are shorted, I just deleted the parts in the middle where DavMail was synchronizing my 1900+ contacts rofl. And I also changed some private/personal information


[android_davmail.log](https://github.com/mguessan/davmail/files/3215665/android_davmail.log)
[debug.txt](https://github.com/mguessan/davmail/files/3215666/debug.txt)
[ios_davmail.log](https://github.com/mguessan/davmail/files/3215667/ios_davmail.log)


.)


 If that's not enough, please come back to me.

**Comment by Exuskazera** [comment]
Update 06-02-2019:

Tried it with several versions of iOS from 8.2 to the newest, the problem is persistent. Logs surprisingly have the identical content, just different IPs and names and versions...

I'm baffled... Android doesn't have such problems. The only difference between those two is when they synchronize. Android seems to start with something else but does the same later on while iOS goes directly to the sync-stuff.

Anyone any ideas? Should I try to contact the apple-support?

Thanks for reading.

**Comment by mguessan** [comment]
You may want to try Apple support, as I don't see anything wrong in DavMail Carddav answer, both Content-Type header and XML body tell the client that content is indeed UTF-8 encoded.

**Comment by jstark1** [comment]
i think we have the same issue here. Exchange 2016 in premise Deployment and we use the davmail.properties:
davmail.enableEws=auto
davmail.url=https://..../owa

the latest working version is 4.8.6-2600. In later versions the contacts with umlauts gets scrambled. The calendar entries with umlauts are working fine.

**Comment by jstark1** [comment]
After some investigations https://stackoverflow.com/questions/13913157/correct-vcard-format-for-ios-devices and https://developer.apple.com/documentation/addressbook/abperson/1458755-init i assume Apple iOS did not support vCard Version 4.0 and the default is to fallback to Version 2.1. 
I've created a fork of the project (https://github.com/jstark1/davmail) witch delivers a vCard Version 3.0 based on the Useragent "iOS/". 

I have no other devices to test and the fork fixed the problem for me.

**Comment by mguessan** [comment]
Thanks for your feedback. I tried to fix this in trunk by disabling VCARD 4.0 and distribution lists with iOS clients. Can you please check this ?

**Comment by jstark1** [comment]
The trunk Version 27 Oct from works for me. Thanks for the fix.

**Comment by mguessan** [comment]
Thanks for your feedback.
