### ISSUE TITLE
Systray icon changed

### ISSUE THREAD

**Issue by stevem6** [mguessan/davmail#37]
In Linux Mint 19.1 Cinnamon, Davmail (5.2.0 or 4.8.3) the icon on the systray is ![Selection_008](https://user-images.githubusercontent.com/21204267/58764338-d3994200-855d-11e9-9717-cf24824f4b88.png)  which looks different from the icons supplied with Davmail instead of the expected usual icon ![org davmail DavMail2](https://user-images.githubusercontent.com/21204267/58764382-2ffc6180-855e-11e9-92ef-340e7cc682d8.png) used in the menu and desktop.

I cannot see anything in the source code or folder icons that would give the changed icon. My question then is, where is the new systray icon coming from?

**Comment by mguessan** [comment]
This is the old JDK tray bug, icon size adjusted for XDG_CURRENT_DESKTOP=X-Cinnamon

If you changed default theme you can adjust background color with:
davmail.trayBackgroundColor

**Comment by stevem6** [comment]
I have finally got round to solving this problem. For others with Linux Mint 19.1 Cinnamon or similar. I'll give my solution. Thanks to [#32 Notification Area icon not properly painted](https://sourceforge.net/p/davmail/bugs/32/) for advice that helped.

The problem is that the tray icon is the wrong size as shown in the first post. In addition there's a black square at the top left of the Desktop, from a balloon notification that isn't displayed properly.

1. In order to use SWT for the correct icon, use Synaptic Manager to install:
libswt-cairo-gtk-3-jni
libswt-gtk-3-java
libswt-gtk-3-jni

2. Download and install the latest version of DavMail from SourceForge.

The two versions of DavMail in Software Manager don't use SWT because Flatpak's version 5.2.0 doesn't see the SWT files installed above. The other version is 4.8.3 and seems to be too old, I presume because it doesn't use the new  _Linux: adjust AWT tray icon for Linux Mint Cinnamon_  in DavGatewayTray.java

**Comment by mguessan** [comment]
Thanks for your feedback, patch released in 5.3.0

**Comment by jdpiguet** [comment]
Running Cinnamon on Ubuntu 22.04 Jammy.
Adding "libswt-cairo-gtk-4-jni libswt-gtk-4-java libswt-gtk-4-jni" solved the problem too.
