### ISSUE TITLE
'Invalid TLS padding data' and 'Unexpected end of ZLIB input stream'

### ISSUE THREAD

**Issue by SanskritFritz** [mguessan/davmail#38]
Davmail 5.2.0 with Thunderbird on Arch Linux.
Today morning I was unable to login to the exchange server due to a certification problem. I switched to non server mode, accepted the new cert interactively. Since that I have the following errors in the log:
```
2019-06-07 16:37:46,878 ERROR [ImapConnection-45156] davmail.exchange.ews.EWSMethod  - Error while parsing soap response: com.ctc.wstx.exc.WstxIOException: Invalid TLS padding data
com.ctc.wstx.exc.WstxIOException: Invalid TLS padding data
Caused by: javax.crypto.BadPaddingException: Invalid TLS padding data
2019-06-07 16:37:46,879 ERROR [ImapConnection-45156] davmail  - [com.ctc.wstx.exc.WstxLazyException] Unexpected end of ZLIB input stream
[com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxIOException: Unexpected end of ZLIB input stream
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
```
Thunderbird is able to get the list into the inbox but most of the mail bodies are not shown.
My question is, where does Davmail store the accepted cert? I want to delete it, and accept the cert again, because my colleague said he had the same login problem in the morning, but did nothing and now it works for him well.

**Comment by SanskritFritz** [comment]
Probably something was wrong server side because today it works perfectly again. Sorry for the noise.

**Comment by SanskritFritz** [comment]
Today we have encountered the same error again. Is there a solution for this that you guys know of?

**Comment by mguessan** [comment]
Basically this message message means the connection stream is closed to early. This may be an issue on Exchange or some other equipment in the middle: proxy, firewall, router...

**Comment by SanskritFritz** [comment]
Thanks for your help. I'll look further in that direction. 
Can this be due to a problematic certificate? Can I somehow reset the cert so I have to accept it again in Davmail?

**Comment by mguessan** [comment]
It's probably not related to certificates, looks more like a network timeout issue.

**Comment by SanskritFritz** [comment]
Thanks for the hint. We still haven't found anything that could have caused the error, however it is gone now for some days again. I'll close this issue again since it can't be davmail's fault.

**Comment by SanskritFritz** [comment]
Just a quick note for the record: I used Davmail without proxy settings. This means I have reached the public OWA through several restrictive proxies and firewalls. Enabling the company proxy in davmail config solved the problem immediately.
