### ISSUE TITLE
Opera M2 Mail Client cannot send

### ISSUE THREAD

**Issue by justingoldberg** [mguessan/davmail#40]
Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850019)
Thread:		davmail.smtp.SmtpServer
Message #:	1
Level:		DEBUG
NDC:			
Category:	davmail
Message:		Connection from /127.0.0.1 on port 1025
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850019)
Thread:		davmail.smtp.SmtpServer
Message #:	2
Level:		INFO
NDC:			
Category:	davmail.connection
Message:		CONNECT - 127.0.0.1:1423 
Location:	davmail.AbstractConnection.logConnection(AbstractConnection.java:158)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850115)
Thread:		SmtpConnection-1423
Message #:	3
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		Test configuration status: 302
Location:	davmail.exchange.ExchangeSessionFactory.checkConfig(ExchangeSessionFactory.java:279)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850116)
Thread:		SmtpConnection-1423
Message #:	4
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 220 DavMail 5.2.0-2961 SMTP ready at Thu Jun 13 09:00:50 EDT 2019
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	5
Level:		DEBUG
NDC:			
Category:	davmail
Message:		< EHLO windows-pc.company.com
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	6
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 250-windows-pc.company.com
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	7
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 250-AUTH LOGIN PLAIN
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	8
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 250-8BITMIME
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	9
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 250 Hello
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	10
Level:		DEBUG
NDC:			
Category:	davmail
Message:		< AUTH PLAIN ********
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850117)
Thread:		SmtpConnection-1423
Message #:	11
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 451 Error : unknown authentication type
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850119)
Thread:		SmtpConnection-1423
Message #:	12
Level:		DEBUG
NDC:			
Category:	davmail
Message:		< RSET
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850120)
Thread:		SmtpConnection-1423
Message #:	13
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 250 OK Reset
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850120)
Thread:		SmtpConnection-1423
Message #:	14
Level:		DEBUG
NDC:			
Category:	davmail
Message:		< QUIT
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850120)
Thread:		SmtpConnection-1423
Message #:	15
Level:		DEBUG
NDC:			
Category:	davmail
Message:		> 221 Closing connection
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:97)
Thrown:

Date:			Thu Jun 13 09:00:50 EDT 2019 (1560430850120)
Thread:		SmtpConnection-1423
Message #:	16
Level:		INFO
NDC:			
Category:	davmail.connection
Message:		DISCONNECT - 127.0.0.1:1423 
Location:	davmail.AbstractConnection.logConnection(AbstractConnection.java:158)
Thrown:

**Comment by mguessan** [comment]
Weird, AUTH PLAIN is definitely working:
```
2019-06-19 12:57:11 DEBUG davmail:97 - > 220 DavMail  SMTP ready at Wed Jun 19 12:57:11 CEST 2019
2019-06-19 12:57:11 DEBUG davmail:97 - < AUTH PLAIN ********
2019-06-19 12:57:11 DEBUG ExchangeSession:182 - Direct EWS authentication
```

**Comment by m1t0s1s** [comment]
SMTP Auth login works. This is the web browser, which uses the same mail code as M2:

![2019-06-22 10_13_21-Task View](https://user-images.githubusercontent.com/48253345/59964994-9843c080-94d6-11e9-8088-b18160c134ea.png)


On a separate issue, IMAP delete does not work in Opera. The deleted email will still appear in Outlook inbox but with a strike through the subject:
![2019_06_22_10_19_58_Task_View](https://user-images.githubusercontent.com/48253345/59965083-aba35b80-94d7-11e9-82d4-cf52cebb3295.png)

**Comment by m1t0s1s** [comment]
SMTP Auth login works. This is the web browser, which uses the same mail code as M2:
![2019-06-22 10_13_21-Task View](https://user-images.githubusercontent.com/48253345/59965098-d988a000-94d7-11e9-812a-f686f5ae56ba.png)



On a separate issue, IMAP delete does not work in Opera. The deleted email will still appear in Outlook inbox but with a strike through the subject:
![2019_06_22_10_19_58_Task_View](https://user-images.githubusercontent.com/48253345/59965100-dbeafa00-94d7-11e9-8cfb-b1b9e13cdd48.png)

**Comment by justingoldberg** [comment]
SMTP Auth login works. This is the web browser, which uses the same mail code as M2:
![2019-06-22 10_13_21-Task View](https://user-images.githubusercontent.com/48253345/59965098-d988a000-94d7-11e9-812a-f686f5ae56ba.png)



On a separate issue, IMAP delete does not work in Opera. The deleted email will still appear in Outlook inbox but with a strike through the subject:
![2019_06_22_10_19_58_Task_View](https://user-images.githubusercontent.com/48253345/59965190-d04c0300-94d8-11e9-8766-f259e56645aa.png)

**Comment by mguessan** [comment]
Well, not enough information to investigate, but I can provide information on IMAP delete with DavMail:

- Default with imapAutoExpunge setting enabled: any message marked \Deleted is automatically deleted (expunged)

- With imapAutoExpunge disabled: messages marked \Deleted are *not* deleted, en explicit EXPUNGE call is required

**Comment by mguessan** [comment]
Thanks for your feedback
