### ISSUE TITLE
Additional padding in EXISTS response

### ISSUE THREAD

**Issue by edwardmbsmith** [mguessan/davmail#41]
When there are 500 or more emails in an inbox `davlib` provides the `EXISTS` response with an additional whitespace padding between the '*' and the 'mail count integer'.

Acceptable response:
```
  58:24.54 > PJJD3 EXAMINE INBOX
  58:24.77 < * 486 EXISTS
```

Unacceptable response:
```
  57:50.86 > KPFE3 EXAMINE INBOX
  57:51.10 < *  953 EXISTS
```

**Comment by mguessan** [comment]
The additional spaces happen with large folders (>500 messages) to avoid client side timeout.

You can disable this in DavMail settingswith:
davmail.enableKeepAlive=false

This will restore RFC compliant behaviour.

**Comment by edwardmbsmith** [comment]
Understand the requirement and appreciate the workaround.

Separately have filed a [bug report](https://bugs.python.org/issue37407) and [pull request](https://github.com/python/cpython/pull/14388) for Python imaplib to be able to account for the additional spaces - assuming the keepalive is a required feature. 

At present I have only tested for one additional space, and hence have updated the regex to filter for one or two spaces. Any condition when more may be possible?

**Comment by mguessan** [comment]
Yes you can have more than two spaces: as IMAP does not have a keepalive mechanism, the idea is to periodically send a single byte (space) on the connection to avoid read timeout on the client side.
