### ISSUE TITLE
URL in Thunderbird calendar setup documentation is missing trailing slash

### ISSUE THREAD

**Issue by chrislong** [mguessan/davmail#45]
The documentation for [Thunderbird calendar setup](http://davmail.sourceforge.net/thunderbirdcalendarsetup.html) says to use a URL like `http://localhost:1080/users/mail@company.com/calendar`, but on my setup with O365Interactive authentication, that results in "no calendar" errors. Thanks to the forum post https://sourceforge.net/p/davmail/discussion/644057/thread/a8c84e58/, I discovered that the URL needs to have a trailing slash (`/`).

Once I added that, it worked with no problems. I don't know if the trailing slash is always needed, but I think the docs should suggest trying it if it fails without it.

**Comment by mguessan** [comment]
/mail@company.com/calendar is for Caldav access
/mail@company.com/calendar/ is a way to get static ical content of the calendar

=> when you create a Caldav calendar in Thunderbird, use http://localhost:1080/users/mail@company.com/calendar
