### ISSUE TITLE
ssl3_get_record:wrong version number by operating openssl command

### ISSUE THREAD

**Issue by yamatakau08** [mguessan/davmail#46]
My environment
Windows 10
Davmail 5.2.0-2961

I can use pop through Davmail
But can't use IMAP.

I checked IMAP communication with Davmail by openssl
I got the following error message.
What is wrong with Davmail?

**5856:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../openssl-1.1.1c/ssl/record/ssl3_record.c:331:**

```
~> uname -a
MINGW64_NT-10.0-17763 XXXXXXXXXXX 3.0.7-338.x86_64 2019-05-27 06:58 UTC x86_64 Msys

~> openssl version
OpenSSL 1.1.1c  28 May 2019

~> openssl s_client -connect localhost:1143 -crlf
CONNECTED(00000168)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
5856:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../openssl-1.1.1c/ssl/record/ssl3_record.c:331:
```

**Comment by mguessan** [comment]
By default DavMail listeners are not encrypted, you should either:
- force your IMAP client to use cleartext communication
- set a server certificate in DavMail settings

**Comment by mguessan** [comment]
Closing issue
