### ISSUE TITLE
Adding a user whitelist

### ISSUE THREAD

**Issue by davidjb** [mguessan/davmail#47]
I've been running Davmail for a while against a shared tenancy (eg Office 365) and have needed to restrict my Davmail server instance down from allowing all users, as it does by default, because if I didn't, anyone from any organisation on O365 would be able to use my server and push data through it.  Whether they would or not is a different story (eg I could MiTM their accounts, which is probably deterrent enough but still...).

However, in short, to avoid effectively what could be considered an open proxy is something I've done with this patch (from Davmail 4.7.x):  

https://github.com/davidjb/djb.davmail/blob/master/patches/davmail-userwhitelist.patch
```java
diff --git a/src/java/davmail/exchange/ExchangeSession.java b/src/java/davmail/exchange/ExchangeSession.java
index 88f3e3a..e2ad6f2 100644
--- a/src/java/davmail/exchange/ExchangeSession.java
+++ b/src/java/davmail/exchange/ExchangeSession.java
@@ -200,6 +200,16 @@ public abstract class ExchangeSession {
                 }
             }
 
+            //XXX Patched in by davidjb
+            String emailProperty = Settings.getProperty("davmail.allowedUsers");
+            String[] emailsArray = emailProperty.split(",");
+            List<String> emails = Arrays.asList(emailsArray);
+            if (emails.contains(userName) == false) {
+                LOGGER.error("Denied access to user: " + userName);
+                throw new DavMailAuthenticationException("EXCEPTION_AUTHENTICATION_FAILED"); 
+            }
+
+
             DavGatewayHttpClientFacade.setCredentials(httpClient, userName, password);
 
             // get webmail root url
```

Quite hacky but enough to simply reject anyone who wasn't listed in the the special property `davmail.allowedUsers`.  

So, is this a feature that could or would be considered for implementation?  I see that my patch no longer applies cleanly to the latest Davmail master (eg v5.x) so some adjustment or work would be required, so I wanted to ask the question first of a) if it's something that could be implemented and if so, b) where one would put said code these days.

Thanks!

**Comment by mguessan** [comment]
Ok, implemented your suggestion, except I named the property davmail.userWhiteList and value is a comma separated list of emails or domains (user@company.com or @company.com)

**Comment by davidjb** [comment]
@mguessan Brilliant, thank you!  That's much better and far more capable than my interim workaround. 👍

**Comment by mguessan** [comment]
Thanks, closing issue
