### ISSUE TITLE
Telephone Numbers

### ISSUE THREAD

**Issue by Meinsda** [mguessan/davmail#49]
Hello

i use davmail to connect my pbx with the Outlook contact. So if someone calls i see the name in the Display. But sometime i don't see the name but i have the number online.

In the debug log i found why it don't work. My pbx sends a number like this +49123412345678.
 But on the exhange Server the number is stored like +49 (1234) 12345678 or 0043 12341234567 . So i get no result.
Is it possible that davmail compares the number in international Format and remove all not number Chars?

**Comment by mguessan** [comment]
I can confirm DavMail does not change anything on values, thus your client (over LDAP ?) is supposed to use the value stored in Exchange. Is there any way to normalize your contact phones ?

**Comment by mguessan** [comment]
Closing issue, DavMail should not mess with user data
