### ISSUE TITLE
davmail unable to get released version

### ISSUE THREAD

**Issue by mtrehans** [mguessan/davmail#51]
davmail is populating the error message : unable to get released version. Also it is showing unable to bind server socket imap on port 1143 port not allowed in use by another process.

Where DavMail is using in between the IMPAP server and PAM Application.

Do let me know if there is workaround or solution on this or you require more information.

**Comment by mguessan** [comment]
Sorry, I really don't understand your report. Would need more details on what you are trying to do and how.
