### ISSUE TITLE
Authentication fails with v5.3.0

### ISSUE THREAD

**Issue by fschrempf** [mguessan/davmail#52]
After upgrading to v5.3.0 I get "Authentication failed: invalid user or password". After downgrading to v5.2.0 everything works fine again.

**Comment by s-p-turner** [comment]
For the record, I upgraded from 5.2.0 to the current tip of master (9f4f822e) earlier today. This is one commit ahead of the one tagged as 5.3.0 (1feacf03) and I didn't encounter any issues with authentication.

**Comment by mguessan** [comment]
Thanks for your feedback, see my comment at https://sourceforge.net/p/davmail/bugs/716/ to help me fix this

**Comment by fschrempf** [comment]
For me this is fixed by 0a34c6c4ea12e9c5cf1594a73dd707852625da61. Thanks!
