### ISSUE TITLE
Invalid Or Unicode Characters

### ISSUE THREAD

**Issue by justingoldberg** [mguessan/davmail#53]
I noticed that the slash unicode character shows up like this (tested in thunderbird and Opera Mail):

"VM_xF8FF_AA Recordings" should be "VM/AA Recordings"

![image](https://user-images.githubusercontent.com/6743293/62703721-d0845d00-b9b7-11e9-9ccd-246925113bc9.png)

Since outlook 2016 is unicode internally by default, I guess that there's not really an easy fix.

**Comment by mguessan** [comment]
Well, the xF8FF is the workaround for invalid characters in folder names (over IMAP).
Without it you would not be able to access those folders

**Comment by justingoldberg** [comment]
I see.
