### ISSUE TITLE
davmail.proxyPassword is stored in plain text

### ISSUE THREAD

**Issue by SanskritFritz** [mguessan/davmail#54]
Is there a way to encrypt it in the properties file?

**Comment by mguessan** [comment]
No there is not... and this wouldn't make much sense: where would you put the encryption key ?
Anyway, on a shared unix instance you should probably chmod go-rwx .davmail.properties

**Comment by SanskritFritz** [comment]
I don't know how other programs do it, but for example cntlm solved this somehow by requiring an extra step:

>        -H     Use this option to get hashes for password-less configuration. In this mode, cntlm prints the results and  exits. You  can  just copy & paste right into the config file.

**Comment by mguessan** [comment]
This is based on pass the hash attack, see https://en.wikipedia.org/wiki/Pass_the_hash
=> basically NTLM hash _is_ the password, you can use it to authenticate over CIFS.

Won't work with other authentication methods.

**Comment by SanskritFritz** [comment]
On nice, thank you. I'll try to learn more about this, honestly I'm not really educated in this area. Anyway, thanks for your time and again thanks for DavMail!
/me off to install the new version :smile:
