### ISSUE TITLE
Authentication required return code -- wrong?

### ISSUE THREAD

**Issue by cslux** [mguessan/davmail#59]
https://github.com/mguessan/davmail/blob/c30b238746a6e0b731429455924c9202024d7366/src/java/davmail/smtp/SmtpConnection.java#L129

Shouldn't it return 530 instead of 503?

**Comment by mguessan** [comment]
No, you can't send mail without authentication in DavMail.

**Comment by cslux** [comment]
Hmm, ok. Here is why I ask. I use Emacs, mu4e and mbsync (isync) for email. However, when tried to sent an email it failed because of the unexpected return code 530 (davmail site). After some investigation I found out that the Emacs build in library smtpmail.el (https://github.com/emacs-mirror/emacs/blob/master/lisp/mail/smtpmail.el#L850	) is expecting a return code 530 in case authentication is required. When i change it to 503 everything is working. Now I don't know which code should be send. I didn't find any smtp standard which contains the correct answer.

On September 16, 2019 8:55:11 PM UTC, "Mickaël Guessant" <notifications@github.com> wrote:
>No, you can't send mail without authentication in DavMail.

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by cslux** [comment]
Ok, I found the correct answer in https://www.ietf.org/rfc/rfc4954.txt.

```
   530 5.7.0  Authentication required

   This response SHOULD be returned by any command other than AUTH,
   EHLO, HELO, NOOP, RSET, or QUIT when server policy requires
   authentication in order to perform the requested action and
   authentication is not currently in force.
```

I'll open an issue on sourceforge.

**Comment by mguessan** [comment]
Ok, let's try this fix, should not have any impact on other SMTP clients
