### ISSUE TITLE
Kerberos / GSSAPI not listed in IMAP4 CAPABILITY

### ISSUE THREAD

**Issue by infabo** [mguessan/davmail#6]
Davmail IMAP should list something like

`> * OK [CAPABILITY IMAP4REV1 AUTH=GSSAPI IDLE MOVE] IMAP4rev1 DavMail 4.9.0-2652 server ready`

when `Kerberos` is enabled in settings. Thunderbird otherwise refuses to connect with Kerberos/GSSAPI selected.

**Comment by mguessan** [comment]
DavMail is not a kerberos gateway (this would imply it would act as the end user, and be declared in Active Directory). It's just a Kerberos client, that relies on current session kerberos ticket to authenticate with Exchange.

=> in order to use DavMail in Kerberos mode, you should *not* configure Thunderbird for Kerberos authentication, see:
http://davmail.sourceforge.net/kerberos.html

**Comment by infabo** [comment]
Does not work either. DavMail just refuses to connect even though a session-ticket is active (see `klist`). Even better, DavMail insists for a password....

**Comment by mguessan** [comment]
I guess you already enabled Kerberos in DavMail settings. You must indeed provide a password on the client side, even if it's not used with Kerberos authentication.

Next step may be to enable jgss debug with:
`-Dsun.security.krb5.debug=true`

**Comment by infabo** [comment]
I think davmail does not even try kerberos. I have called `davmail` with `-Dsun.security.krb5.debug=true` params. but davmail-log-windows does not provide anything special.

Why I think kerberos is not used:

```
Date:			Wed May 08 09:44:36 CEST 2019 (1557301476409)
Thread:		SmtpConnection-36792
Message #:	22
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		Direct EWS authentication
Location:	davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:183)
Thrown:
```

```
Date:			Wed May 08 09:44:36 CEST 2019 (1557301476457)
Thread:		SmtpConnection-36792
Message #:	23
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		Authentication failed: invalid user or password
Location:	davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:274)
Thrown:
```

**Comment by infabo** [comment]
I change "Exchange Protocol" from "EWS" to "Auto". Now I can see kerberos related output in the log.

**Comment by mguessan** [comment]
Confirmed and fixed in trunk, kerberos support was disabled in direct EWS mode.

Thanks for your feedback.
