### ISSUE TITLE
5.3.1 - inbox sync issues when another device deletes a message

### ISSUE THREAD

**Issue by pcause** [mguessan/davmail#60]
I am running 5.3.1 with evolution.  If a message gets deleted from a different device and i try to open that on evolution I get a message about empty cache file.  mailbox then has trouble syncing.

**Comment by mguessan** [comment]
First question:  I thought Evolution had native Exchange / O365 support ?

On sync issue: any time you select a folder, DavMail will detect that target folder changed and will reload message list with flags.
If you try to fetch a message that no longer exists, you will get an IMAP error.
