### ISSUE TITLE
IMAP UID SEARCH non-compliant response

### ISSUE THREAD

**Issue by maxhille** [mguessan/davmail#61]
As I was encountering a problem with DavMail and an IMAP client, I tried to find out what is wrong. The issue I found was a non-compliant response like this (via wireshark):

```
Jce5lw UID SEARCH CHARSET "UTF-8" 1:*
Jce5lw BAD unable to handle request: Unsupported charset "UTF-8"
```

Now this is exactly the issue described a while ago in https://sourceforge.net/p/davmail/bugs/631/, but the patch back then does not seem to have helped?

version: 5.1.0.2891

**Comment by mguessan** [comment]
Well, I would first try with latest version: 5.3.1

**Comment by mguessan** [comment]
Working for me, closing issue

**Comment by tleonardi** [comment]
I'm still having the same issue with davmail 5.4.0
Happy to provide more info if needed!

**Comment by tleonardi** [comment]
sent, thanks!

**Comment by mguessan** [comment]
For the record: this was a quoting issue.

**Comment by ndarwincorn** [comment]
@mguessan - can you elaborate? I'm seeing the same thing with aerc as the mail client and davmail 5.4.0-3135.

**Comment by mguessan** [comment]
This means it's fixed in trunk, please check https://github.com/mguessan/davmail#trunk-builds

**Comment by ndarwincorn** [comment]
Much appreciated, I should've dug deeper into the svn log that's my bad
