### ISSUE TITLE
DavMail causes Thunderbird to forget credentials on network error (?)

### ISSUE THREAD

**Issue by attila123** [mguessan/davmail#62]
Hi,
Using davmail 5.3.1 (installed from Arch Linux User Repository (AUR): https://aur.archlinux.org/packages/davmail/) to access my o365 calendar from thunderbird. So protocol is EWS and URL is https://outlook.office365.com/EWS/Exchange.asmx.
Sometimes I got a dialogue box to enter my username and password again, even though I check the "remember" checkbox.
![image](https://user-images.githubusercontent.com/1728046/66874494-8e752a00-efab-11e9-92ec-b29eebe272ae.png)

When I simply exit DavMail and start again, the problem does not happen.
So I think the problem happens when DavMail cannot connect to the service for some network reason (e.g. there may be an issue that I bring my laptop home to normal Internet and the company proxy is still in effect (I run a transparent proxy redirector (whatever it is called) service based on redsocks2 and iptables)).

In this case davmail should not automatically assume that my credentials got invalid and should not forget those. It is OK to bring up a dialog, but it should have 2 options: 1. reconnect 2. change credentials.
Better yet, (optionally) it should try to reconnect periodically based on some settings.
I can try to collect some logs for this if needed.

Update: attaching 
[davmail_log.txt](https://github.com/mguessan/davmail/files/3731698/davmail_log.txt)
log when it happened. I replaced my email in the logs and in the screenshot.

**Comment by mguessan** [comment]
According to your log file DavMail sends:
`HTTP/1.1 503 Service Unavailable`
on network error.
This looks like the right answer: an authentication error would return a 401, which would indeed invalidate current credentials.

**Comment by mguessan** [comment]
According to your log file DavMail returns 503 and not 401, so Thunderbird should *not* detect an authentication failure.

**Comment by mguessan** [comment]
Closing issue as it looks like this is a client side issue
