### ISSUE TITLE
davmail eats CPU while doing nothing

### ISSUE THREAD

**Issue by Ri0n** [mguessan/davmail#66]
I closed my Thunderbird just to check if davmail still does something and it seems it never stop consuming cpu

![image](https://user-images.githubusercontent.com/52379/67485070-09a4a300-f672-11e9-8e43-db103eb7e171.png)

**Comment by mguessan** [comment]
Did not reproduce this, however Java has a background thread to manage garbage collection

**Comment by Ri0n** [comment]
Already doesn't matter. I quit the company where I needed your product.
But IIRC it never stopped eating cpu. Maybe related to some specific versions of java.
Thanks for the review anyway.
