### ISSUE TITLE
Missing parameters on POST preventing login

### ISSUE THREAD

**Issue by aembleton** [mguessan/davmail#68]
I am connecting to an OWA site provided by my employer.  When I login from that in Firefox, I can see that a POST is made with the following credentials filled out

- `curl`
- `curlid`
- `curlmode`
- `pubpriv`
- `username`
- `password`
- `submit`

There is also passphrase and pin that aren't filled out.  `curl` and `curlid` appear to be some randomised number, probably to make it harder for tools like davmail.  When davmail connects, it leaves `curl` and `curlid` empty.  `curlmode` is set to 0 which is the same as Firefox.  `pubpriv` (a flag to say if this is a public or private machine) is not set.  `username` and `password` are as expected.  `submit` is not set, but in Firefox it is Log+On.  Davmail also sets `trusted` and `flags` to 4.

The result of this is Davmail receiving a 401:
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="DavMail Gateway"
Connection: keep-alive
Content-Length: 0
```

I think `pubpriv` needs to be set to 1 (same as Firefox).  I'm not sure how `curl` and `curlid` values are generated, but I guess its some JS.

**Comment by mguessan** [comment]
Not easy to reproduce without access to target Exchange server. If you manage to find a way through the custom authentication this can be implemented in DavMail through a custom Authenticator.

**Comment by mguessan** [comment]
Closing issue, please reopen if you manage to build a valid authentication sequence

**Comment by aembleton** [comment]
> this can be implemented in DavMail through a custom Authenticator.

Is there any documentation about this?  Or is this a case of adding it to the Davmail source code and compiling?

**Comment by mguessan** [comment]
Building DavMail is easy, check Appveyor and Travis config for details.
You can set a custom authenticator with davmail.authenticator key in DavMail settings.

In order to build a custom authenticator, the best place to start is definitely standard authenticators, e.g. form based authenticator at:
https://github.com/mguessan/davmail/blob/master/src/java/davmail/exchange/auth/ExchangeFormAuthenticator.java
