### ISSUE TITLE
Build Instructions for Linux, specifically Fedora please

### ISSUE THREAD

**Issue by SteveEbey73742** [mguessan/davmail#72]
What dependencies, and other tools do I need to compile this on Fedora 31?

**Comment by mguessan** [comment]
Please check the spec file in DavMail source, or just grab the RPM from
https://copr.fedorainfracloud.org/coprs/mguessan/davmail/build/1092062/

The source RPM is built by OpenSuse at:
https://software.opensuse.org//download.html?project=home%3Amguessan%3Adavmail&package=davmail
