### ISSUE TITLE
Homeset and calendar collection share the name name

### ISSUE THREAD

**Issue by Chewie** [mguessan/davmail#75]
Hello,

Initially discovered here: https://forums.bitfire.at/topic/2177/davmail-only-extra-calendars-are-synced/3

It appears that davmail reports the same collection (https://xxxx:1080/users/xxx@xxx/calendar/) as both a homeset and a calendar, confusing davx5.

As suggested, I'm raising an issue here to understand if this is an error or working as intended.

Cheers,

**Comment by mguessan** [comment]
Well, it used to work, see:
http://davmail.sourceforge.net/androiddavdroidsetup.html

I haven't updated for a while so this may be a regression.

Anyway, the /principals namespace was implemented for OSX compatibility => should work fine with other Caldav clients.

Did you try to change calendar-home-set on DavMail side ?

**Comment by bmmeijers** [comment]
I am running into the same issue. Extra calendars synced with DAVx5 show up fine, but the main calendar of Exchange does not show up at all. I like 

What do you mean with:

> Did you try to change calendar-home-set on DavMail side ?

Is there a setting that allows this to be changed inside DavMail?

**Comment by rfc2822** [comment]
According to [RFC 4791 6.2.1](https://tools.ietf.org/html/rfc4791#section-6.2.1), it seems that the home-set may as well be a calendar collection itself:

>6.2.1.  CALDAV:calendar-home-set Property
>[…]
>This property specifies the URL of collections that *are either calendar collections* or ordinary collections that have child or descendant calendar collections owned by the principal.

So this was probably a DAVx⁵ problem and has been fixed there (in 2.6.3-beta6).

**Comment by bmmeijers** [comment]
I can confirm that DAVx⁵ 2.6.3 solves this issue (and shows also calendars and address books in the homeset root of the Exchange user exposed by DavMail).

**Comment by mguessan** [comment]
Thanks for your feedback, we can close this issue on DavMail side, right ?

**Comment by bmmeijers** [comment]
I think so.
