### ISSUE TITLE
davmail doesn't honor multi-display configurations

### ISSUE THREAD

**Issue by Ri0n** [mguessan/davmail#8]
I have two monitors and and davmail always opens its windows such a way that partially it's on one display and partially on another.

So I have to move the windows all the time.

**Comment by mguessan** [comment]
Working fine under windows... anyway I changed the way to set frame location
=> fix available in trunk

**Comment by Ri0n** [comment]
Yes not it's somewhat better. But now o365interactive confirmation window appears behind of other windows. Probably it's something about stealing focus but it didn't even flashed on taskbar. So it was hard to notice.
KDE Plasma here.

**Comment by mguessan** [comment]
Please check again with latest build

**Comment by Ri0n** [comment]
Just tried trunk deb. If DavMail main window is active then mfa window will be brought up. That's ok.
But if for example I start davmail, then click "get messages in thunderbird" then mfa window will be opened behind Thunderbird and it won't flash on taskbar.

**Comment by mguessan** [comment]
KDE focus stealing prevention prevents DavMail from stealing focus.
=> disabling it lets DavMail bring frame to top

**Comment by Ri0n** [comment]
is it possible to implement https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/ ?
Usually clicks on popups do really bring windows to foreground.

**Comment by mguessan** [comment]
Well, you can send an RFE to OpenJDK, they have the API (TaskBar) but not the linux implementation.

**Comment by Ri0n** [comment]
Do you mean it is not acceptable to use 3rdparty libraries like https://github.com/munterkalmsteiner/StatusNotifierItemJava?
I'm sorry but I understand nothing in Java programming and its libraries.
