### ISSUE TITLE
O365Modern authentication is broken since commit b480657f329e35598262c384cd19c139ccc80fcf

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [mguessan/davmail#80]
Hi,

I tried to rebase my own copy of davmail after my pull requests got merged. Right now for me it seems all broken (ie it builds, but the davmail server, with the same config, seems to be completely broken, very single step like 0365Modern authentication seems to be broken.

After bisecting, it looks like the commit I used (f6c53a68332b439120f15ffbc39bc0a4d259cbb6) is working, while the next one (b480657f329e35598262c384cd19c139ccc80fcf) changing HTTP exception broke it all. I see you did remove the class GetRequest in this commit, is this expected (it seems unrelated to the initial purpose of this commit which was using recent exceptions) ?

Cheers,
Romain

**Comment by mguessan** [comment]
Thanks for your feedback, you nailed it: it's related to GetRequest/HttpGet difference.

I am in the middle of a major refactoring to move to HttpClient 4 and still struggling with some subtleties of the new version.

Should be fixed now, please let me know if you still have issues.

**Comment by Romain-Geissler-1A** [comment]
Ok I did fetch the current master 5 minutes ago, and indeed now without changing my config it works. Thanks ! Even the default User agent now works, I don't need to override it anymore.

As soon as there will be a new release of Davmail and that Ubuntu will pick it (hopefully before Ubuntu 20.04 LTS is released), then I won't need to rebuild the .deb package myself ;)
