### ISSUE TITLE
Unable to build davmail from source after pulling Fri Jan 3 commits 2fc947a8 and ccf4ca49.

### ISSUE THREAD

**Issue by s-p-turner** [mguessan/davmail#81]
Build output is attached.
[davmail-error.txt](https://github.com/mguessan/davmail/files/4025251/davmail-error.txt)

**Comment by mguessan** [comment]
Building fine on AppVeyor.

You are probably missing the git-svn package, used to retrieved current trunk commit id from git repo

**Comment by s-p-turner** [comment]
Hi Mickaël,

You are correct - I was missing the git-svn package.

Thanks and regards.

Steve
