### ISSUE TITLE
DavMail should check its libraries versions and inform about possible problems

### ISSUE THREAD

**Issue by Ri0n** [mguessan/davmail#9]
As a follow up of https://github.com/mguessan/davmail/issues/7

If DavMail can detect that the swt version is somehow buggy, it should warn about it and better avoid initialization of any its classes.

The same jdk/jre.
I'm especially interested in O365Interactive here which wasn't available with some java versions.
It's better to draw it in gray and explain why it's not available right in the application then force people to read all kinds of documents. Or at least put a link into ui to the protocols description with some comment like "there could be more methods".

**Comment by Ri0n** [comment]
I just noticed your commit https://github.com/mguessan/davmail/commit/b5f49dc4f187a5f1d3ad5ef9fe4213b62fbb0f07
So you already partially addressed the issue. That's great!

**Comment by mguessan** [comment]
Well, supporting all cases is tricky, I try to block the most obviously wrong combinations, but this is a moving target: currently Java 11 / OpenJFX 11 is not available on linux, but will be in the near future.

Please also note that O365Interactive is brand new, I do not have much feedback on it yet.

**Comment by mguessan** [comment]
DavMail O365 interactive will work with most Java versions in next release
=> closing this issue

**Comment by Ri0n** [comment]
Thanks

**Comment by Ri0n** [comment]
Just checked with OpenJDK 11. Interactive method is absent there. So I switched back to OpenJDK 8.
Btw strange thing. after this switch forward and back previously not working tray appeared in tray, but now it crashes the application on click.

**Comment by Ri0n** [comment]
Hm just restarted davmail and again no tray icon. some magic I guess.
