### ISSUE TITLE
Shared mailboxes in office 365 don't work

### ISSUE THREAD

**Issue by neilkatin** [mguessan/davmail#90]
I'm am running against a hosted outlook365 instance with modern auth and 2FA.  I was not able to get shared mailboxes working.

I could set my IMAP Path to the /users/sharedmailbox@domain.com setting; all subfolders worked but the INBOX was the login user's mailbox, not the shared mailbox.

I could not find a variation of username to set for the other alternative: domain/user/shared@domain was always rejected by the two factor auth screens.

I made a small change to davmail/imap/ImapConnection.java to fix this.  It basically accepts usernames like 'user//shared' as a user name and a shared mailbox name (without a separate domain).  This fixed the problem for me.

I will submit a pull request with the change so you can examine it.

(All my testing was using Thunderbird 68.5), on both Windows and Linux.

**Comment by mguessan** [comment]
Makes sense, need to test this on a shared mailbox to confirm.

**Comment by mguessan** [comment]
Fixed in trunk
