### ISSUE TITLE
Authentication Error - Check your username and password.

### ISSUE THREAD

**Issue by linuxiaobai** [mguessan/davmail#95]
Hello,

I configured the Davmail (v5.4) and mailspring (1.7.2), and I encounter
![Screenshot from 2020-03-08 14-26-54](https://user-images.githubusercontent.com/21261930/76158174-fb04e700-614d-11ea-9c96-943914dcea04.png)
 the error message "Authentication Error - Check your username and password.". I am for sure that my password is correct. EWS URL is https://outlook.office365.com/EWS/Exchange.asmx
![Screenshot from 2020-03-08 13-56-22](https://user-images.githubusercontent.com/21261930/76158168-d7da3780-614d-11ea-9c64-09d72c722119.png)

**Comment by mguessan** [comment]
According to your URL you have an Office 365 mailbox. There is a strong chance that basic authentication is no allowed by your admins (Microsoft deprecated basic authentication on EWS endpoint a while ago).
=> you can check this by accessing https://outlook.office365.com/EWS/Exchange.asmx in a web browser

If this works you should be able to authenticate with DavMail with your login/password
If not you will probably have to switch to modern authentication (i.e. Oauth 2)
O365Modern: Oauth authentication without user interaction, does not support all use cases
O365Interactive: Oauth authentication with an embedded browser window, requires OpenJFX support
O365Manual: Oauth authentication with an external browser

**Comment by linuxiaobai** [comment]
Thank you very much for your reponse. When I open the link: https://outlook.office365.com/EWS/Exchange.asmx, it prompt me to enter user name and password, and then the following page showed. 
![IMG_20200309_231302](https://user-images.githubusercontent.com/21261930/76228638-f4649580-625b-11ea-9ebc-d0025ff10924.jpg). Do you think if I have ews acess? Also yesterday I tried testconnect using above ews address, and it is successful. https://www.testconnectivity.microsoft.com/

**Comment by mguessan** [comment]
Looks good, you should be able to use O365 mode to access Office365 with DavMail.

**Comment by linuxiaobai** [comment]
I have tried o365 but no luck, still the same message showed.

**Comment by linuxiaobai** [comment]
Not sure if our admin made some setting and block the access. I can login my account using the address mail.office365.com

**Comment by linuxiaobai** [comment]
When I use web interface, I only input my email adress and password, and no additional information is needed, like pingid.

**Comment by mguessan** [comment]
You mean direct EWS access in your web browser is no longer working ?
This is the case for most O365 tenants, you will have to switch to Oauth (modern) authentication, please try those modes in DavMail.

**Comment by linuxiaobai** [comment]
thank you, now I can connect to my office365 account. the issue is caused by oauth2. I found this solution after tracking the log. it indicates that I need open 1 url to give the auth to the davmail. After that, it works!!!

**Comment by mguessan** [comment]
Great, thanks for your feedback

**Comment by 5e1f** [comment]
i've got similar problem with new version 5.5, Thunderbird (Linux) and Exchange of my organization.
In version 5.4 all works fine, but after update to 5.5 i've got error "Authentication failed: invalid user or password". Link https://my_organization_domain/EWS/Exchange.asmx in a web browser opens fine (with my credentials)
After rollback to 5.4 again all is ok

**Comment by 5e1f** [comment]
Difference in logs
v.5.4
2020-04-16 22:47:46,609 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:45418 
2020-04-16 22:47:49,634 INFO  [ImapConnection-45418] davmail.connection  - LOGON - 127.0.0.1:45418 **mydomain-nt\my.login** 

v.5.5
2020-04-16 22:44:01,694 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:45330 
2020-04-16 22:44:03,172 INFO  [ImapConnection-45328] davmail.connection  - FAILED - 127.0.0.1:45328 **mydomain-nt**
2020-04-16 22:44:03,176 ERROR [ImapConnection-45328] davmail  - Authentication failed: invalid user or password
davmail.exception.DavMailAuthenticationException: Authentication failed: invalid user or password
	at davmail.exchange.ews.EwsExchangeSession.checkEndPointUrl(EwsExchangeSession.java:240)
	at davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:249)
	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:177)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:196)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:99)
	at davmail.imap.ImapConnection.run(ImapConnection.java:140)

**Comment by 5e1f** [comment]
So  i've just change "mydomain-nt\my.login" to "my.login" in my Thunderbird account settings and now everything is ok ;)

**Comment by mguessan** [comment]
There *is* a regression, see https://github.com/mguessan/davmail/issues/100

**Comment by averter** [comment]
> thank you, now I can connect to my office365 account. the issue is caused by oauth2. I found this solution after tracking the log. it indicates that I need open 1 url to give the auth to the davmail. After that, it works!!!

Can you give me more details about how you found the url + your current setup? Are you on o365 or EWS? Thanks
